# Based on bokeh appveyor set up
build: false

platform:
  - x64

environment:
  matrix:
    - MINICONDA: C:\Miniconda36-x64
      CONDA_ENV: py36

skip_branch_with_pr: true
clone_depth: 5
skip_tags: true

init:
  - cmd: set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%
  - cmd: echo %path%

install:
  - powershell .\\ci\\appveyor\\install.ps1

build_script:
  - powershell .\\ci\\appveyor\\build.ps1

test_script:
  - powershell .\\ci\\appveyor\\test.ps1

